// info harus berjumlah 2 lebih sedikit dari baris
// baris harus dimulai dari 0
// dan nilai baris harus semakin tinggi min 6 lebih banyak dari sebelumnya

var garis = [0, 30, 50, 73, 100, 115, 127, 155, 165, 191]
var info = [
	['1. Hanya Berniat Mengangkut Pasukan Jepang', 'Amir Syarifuddin, Menteri Penerangan saat itu, berpesan agar pemerintah daerah di Surabaya menerima niat baik dan membantu tugas tentara sekutu yang tergabung dalam AFNEI (Allied Forces Netherlands East Indies) itu. Akan tetapi, rakyat Surabaya tidak percaya begitu saja. Bung Tomo termasuk orang pertama yang tidak percaya.'],
	['2. Ajak Berunding', 'Menjelang kedatangan tentara Inggris di Surabaya, Drg Moesopo, Menteri Pertahanan RI, mengajak rakyat Surabaya untuk perang dengan pasukan Inggris. Namun, ternyata tentara Inggris yang datang juga membawa misi mengembalikan Indonesia kepada administrasi pemerintahan Belanda sebagai negeri jajahan Hindia Belanda. NICA ikut membonceng bersama rombongan tentara Inggris untuk tujuan itu. Tak lama berselang setelah kapal Inggris merapat di Tanjung Perak, Surabaya, dua orang perwira staf Mallaby (Komandan Kerajaan Inggris) menemui Gubernur Soerjo.'],
	['3. Menduduki Banyak Tempat Strategis', 'Dalam perundingan antara sekutu dan Indonesia, pada 26 Oktober di Gedung Kayoon, menghasilkan kesepakatan, di antaranya pasukan sekutu hanya akan melucuti senjata Jepang saja. Nyatanya, Inggris juga menduduki sejumlah tempat strategis di luar perjanjian. Misalkan di lapangan terbang Tanjung Perak, perusahaan listrik Gemblongan, kantor pos besar dan gedung studio radio di Simpangan. Tindakan Inggris itu dianggap kurang ajar oleh Bung Tomo karena tidak sesuai perjanjian.'],
	['4. Inggris Menyerbu Penjara', 'Pasukan Inggris juga menyerbu penjara Kalisosok dan membebaskan orang Belanda yang sempat ditawan pejuang kemerdekaan. Tentara Inggris mulai menunjukkan ketidakpatuhan pada perjanjian yang telah dibuat sebelumnya. Pada 27 Oktober, menuntut dan mengancam semua rakyat Surabaya agar menyerahkan kembali semua senjata dan peralatan perang kepada Inggris.'],
	['5. Tewasnya Brigjen Mallaby', 'Pada 30 Oktober 1945 menjadi hari naas bagi Brigjen Mallaby. Saat dirinya hendak melintas Jembatan Merah, sejumlah milisi Indonesia mencegat mobilnya. Di situ, terjadilah baku-tembak dari kedua belah pihak. Brigjen Mallaby pun tewas di tempat.'],
	['6. Respons Jakarta Pasif', 'Para pemimpin di Surabaya, termasuk Bung Tomo pun kemudian menghubungi Jakarta untuk meminta petunjuk. Namun, Presiden Soekarno dan Menteri Luar Negeri Soebardjo menyerahkan keputusan sepenuhnya kepada rakyat Surabaya. Bung Tomo, pimpinan BPRI, pun tak ada pilihan kecuali bertempur.'],
	['7. Petikan Pidato Bung Tomo Membakar Semangat Arek-arek Surabaya', 'Beberapa petikan pidato Bung Tomo yang membakar semangat rakyat Surabaya. “Inilah jawaban kita, jawaban pemuda-pemuda rakyat Indonesia. Hai Inggris, selama banteng-banteng, pemuda-pemuda Indonesai masih mempunyai darah merah yang dapat membuat secarik kain putih menjadi merah dan putih, selama itu kita tidak akan menyerah.” “Teman-temanku seperjuangan, terutama pemuda-pemuda Indonesia, kita terus berjuang, kita usir kaum penjajah dari bumi kita Indonesia yang kita cintai ini. Sudah lama kita menderita, diperas, diinjak-injak,”'],
	['8. Libatkan Rakyat Surabaya', 'Pertempuran 10 November merupakan pertempuran yang sangat besar karena tidak hanya melibatkan unusr pasukan bersenjata saja, melainkan juga segenap warga Surabaya.']
]